[package]
name = "range-set"
version = "0.1.0"
authors = ["Joe Neeman <joeneeman@gmail.com>"]

[dependencies]
itertools = "0.4"
num = "0.1"

[dev-dependencies]
quickcheck = "0.2"
quickcheck_macros = "0.2"
