[package]
name = "range-map"
version = "0.1.1"
authors = ["Joe Neeman <joeneeman@gmail.com>"]

[dependencies]
itertools = "0.4"
num = "0.1"

[dev-dependencies]
quickcheck = "0.2"
quickcheck_macros = { git = "https://github.com/BurntSushi/quickcheck" }
